height=input("Please enter your height in meters!\n")
updHeight=float(height)
weight=input("Please enter your weight in kilograms!\n")
updWeight=float(weight)
bmi=updWeight/(updHeight*updHeight)
print("Your BMI is ",bmi)